// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { addPet, createUser, createUsersWithArrayInput, createUsersWithListInput, deleteOrder, deletePet, deleteUser, findPetsByStatus, findPetsByTags, getInventory, getOrderById, getPetById, getUserByName, loginUser, logoutUser, type Options, placeOrder, updatePet, updatePetWithForm, updateUser, uploadFile } from '../sdk.gen';
import type { AddPetData, CreateUserData, CreateUsersWithArrayInputData, CreateUsersWithListInputData, DeleteOrderData, DeletePetData, DeleteUserData, FindPetsByStatusData, FindPetsByStatusResponse, FindPetsByTagsData, FindPetsByTagsResponse, GetInventoryData, GetInventoryResponse, GetOrderByIdData, GetOrderByIdResponse, GetPetByIdData, GetPetByIdResponse, GetUserByNameData, GetUserByNameResponse, LoginUserData, LoginUserResponse, LogoutUserData, PlaceOrderData, PlaceOrderResponse, UpdatePetData, UpdatePetWithFormData, UpdateUserData, UploadFileData, UploadFileResponse } from '../types.gen';

/**
 * uploads an image
 */
export const uploadFileMutation = (options?: Partial<Options<UploadFileData>>): UseMutationOptions<UploadFileResponse, AxiosError<DefaultError>, Options<UploadFileData>> => {
    const mutationOptions: UseMutationOptions<UploadFileResponse, AxiosError<DefaultError>, Options<UploadFileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadFile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Add a new pet to the store
 */
export const addPetMutation = (options?: Partial<Options<AddPetData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AddPetData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AddPetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addPet({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update an existing pet
 */
export const updatePetMutation = (options?: Partial<Options<UpdatePetData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UpdatePetData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UpdatePetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updatePet({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const findPetsByStatusQueryKey = (options: Options<FindPetsByStatusData>) => createQueryKey('findPetsByStatus', options);

/**
 * Finds Pets by status
 *
 * Multiple status values can be provided with comma separated strings
 */
export const findPetsByStatusOptions = (options: Options<FindPetsByStatusData>) => queryOptions<FindPetsByStatusResponse, AxiosError<DefaultError>, FindPetsByStatusResponse, ReturnType<typeof findPetsByStatusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await findPetsByStatus({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: findPetsByStatusQueryKey(options)
});

export const findPetsByTagsQueryKey = (options: Options<FindPetsByTagsData>) => createQueryKey('findPetsByTags', options);

/**
 * Finds Pets by tags
 *
 * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 *
 * @deprecated
 */
export const findPetsByTagsOptions = (options: Options<FindPetsByTagsData>) => queryOptions<FindPetsByTagsResponse, AxiosError<DefaultError>, FindPetsByTagsResponse, ReturnType<typeof findPetsByTagsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await findPetsByTags({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: findPetsByTagsQueryKey(options)
});

/**
 * Deletes a pet
 */
export const deletePetMutation = (options?: Partial<Options<DeletePetData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeletePetData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeletePetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deletePet({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPetByIdQueryKey = (options: Options<GetPetByIdData>) => createQueryKey('getPetById', options);

/**
 * Find pet by ID
 *
 * Returns a single pet
 */
export const getPetByIdOptions = (options: Options<GetPetByIdData>) => queryOptions<GetPetByIdResponse, AxiosError<DefaultError>, GetPetByIdResponse, ReturnType<typeof getPetByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPetById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPetByIdQueryKey(options)
});

/**
 * Updates a pet in the store with form data
 */
export const updatePetWithFormMutation = (options?: Partial<Options<UpdatePetWithFormData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UpdatePetWithFormData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UpdatePetWithFormData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updatePetWithForm({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getInventoryQueryKey = (options?: Options<GetInventoryData>) => createQueryKey('getInventory', options);

/**
 * Returns pet inventories by status
 *
 * Returns a map of status codes to quantities
 */
export const getInventoryOptions = (options?: Options<GetInventoryData>) => queryOptions<GetInventoryResponse, AxiosError<DefaultError>, GetInventoryResponse, ReturnType<typeof getInventoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getInventory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getInventoryQueryKey(options)
});

/**
 * Place an order for a pet
 */
export const placeOrderMutation = (options?: Partial<Options<PlaceOrderData>>): UseMutationOptions<PlaceOrderResponse, AxiosError<DefaultError>, Options<PlaceOrderData>> => {
    const mutationOptions: UseMutationOptions<PlaceOrderResponse, AxiosError<DefaultError>, Options<PlaceOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await placeOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete purchase order by ID
 *
 * For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
 */
export const deleteOrderMutation = (options?: Partial<Options<DeleteOrderData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteOrderData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getOrderByIdQueryKey = (options: Options<GetOrderByIdData>) => createQueryKey('getOrderById', options);

/**
 * Find purchase order by ID
 *
 * For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
 */
export const getOrderByIdOptions = (options: Options<GetOrderByIdData>) => queryOptions<GetOrderByIdResponse, AxiosError<DefaultError>, GetOrderByIdResponse, ReturnType<typeof getOrderByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getOrderById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getOrderByIdQueryKey(options)
});

/**
 * Creates list of users with given input array
 */
export const createUsersWithListInputMutation = (options?: Partial<Options<CreateUsersWithListInputData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateUsersWithListInputData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateUsersWithListInputData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUsersWithListInput({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete user
 *
 * This can only be done by the logged in user.
 */
export const deleteUserMutation = (options?: Partial<Options<DeleteUserData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserByNameQueryKey = (options: Options<GetUserByNameData>) => createQueryKey('getUserByName', options);

/**
 * Get user by user name
 */
export const getUserByNameOptions = (options: Options<GetUserByNameData>) => queryOptions<GetUserByNameResponse, AxiosError<DefaultError>, GetUserByNameResponse, ReturnType<typeof getUserByNameQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserByName({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserByNameQueryKey(options)
});

/**
 * Updated user
 *
 * This can only be done by the logged in user.
 */
export const updateUserMutation = (options?: Partial<Options<UpdateUserData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UpdateUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UpdateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const loginUserQueryKey = (options: Options<LoginUserData>) => createQueryKey('loginUser', options);

/**
 * Logs user into the system
 */
export const loginUserOptions = (options: Options<LoginUserData>) => queryOptions<LoginUserResponse, AxiosError<DefaultError>, LoginUserResponse, ReturnType<typeof loginUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await loginUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: loginUserQueryKey(options)
});

export const logoutUserQueryKey = (options?: Options<LogoutUserData>) => createQueryKey('logoutUser', options);

/**
 * Logs out current logged in user session
 */
export const logoutUserOptions = (options?: Options<LogoutUserData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof logoutUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await logoutUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: logoutUserQueryKey(options)
});

/**
 * Creates list of users with given input array
 */
export const createUsersWithArrayInputMutation = (options?: Partial<Options<CreateUsersWithArrayInputData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateUsersWithArrayInputData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateUsersWithArrayInputData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUsersWithArrayInput({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create user
 *
 * This can only be done by the logged in user.
 */
export const createUserMutation = (options?: Partial<Options<CreateUserData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
